### ISSUE TITLE
embedding compressed py files is malware-like

### ISSUE THREAD

**Issue by gdementen** [salabim/peek#1]
I personally find it a bit of a shame you went for that option because it makes your project look too much like malware. I don't feel comfortable using your otherwise very nice project (much nicer syntax and nice extra features compared to icecream) for that reason.

I would have very much preferred if you split the project in two distinct pieces: the normal project with a few dependencies (or as a second best a few plain-text files) and a single-file *distribution* of the project (stored in another github project) for those who like that single file trick. 

Now I am just a random guy on the internet and I don't expect you to change your project just for me, but I wanted to let you know that some people are put off by that kind of trick.

**Comment by salabim** [comment]
That's a valid point. I am considering adding the dependencies and removing the rather cryptic embedded modules.
Stay tuned.

**Comment by salabim** [comment]
From now on, peek does not contain embedded versions of any module. 
The required dependencies will be automatically installed.

**Comment by gdementen** [comment]
Wow, that was fast. Thanks !
