### ISSUE TITLE
Enhancement: Automatically copy peeked content onto the clipboard

### ISSUE THREAD

**Issue by gahjelle** [salabim/peek#2]
This is an Advent of Code-inspired proposal. I'm not sure if it's worth the extra dependency :)

It could be a small convenience if it's possible to automatically copy the content of a peek onto the clipboard, for example by incorporating https://pypi.org/project/pyperclip/

Then, something along the lines of:

```python
peek(part1, to_clipboard=True)
```

would show the contents of `part1` and copy the value onto the clipboard.

Great project, Ruud!

**Comment by salabim** [comment]
Interesting idea. I'll have a look into it.
Stay tuned.

**Comment by salabim** [comment]
Implemented it in a slightly different way.
Thanks for the suggestion.
Happy AoC-ing ;-)

**Comment by salabim** [comment]
Done
